name: git clone action
description: git clone action
author: RekGRpth
inputs:
  branch:
    description: git clone branch
runs:
  using: composite
  steps:
    - run: |
        set -eux
        export INPUTS_BRANCH="${{ inputs.branch }}"
        export GITHUB_TOKEN="${{ github.token }}"
        "${GITHUB_ACTION_PATH}/action.sh"
      shell: sh
