name: git clone action
description: git clone action
author: RekGRpth
inputs:
  branch:
    description: git clone branch
runs:
  using: composite
  steps:
    - run: |
        set -eux
        GITHUB_BRANCH="${GITHUB_REF##*/}"
        GITHUB_REPOSITORY_NAME="${GITHUB_REPOSITORY##*/}"
        GITHUB_TOKEN="${{ github.token }}"
        INPUTS_BRANCH="${{ inputs.branch }}"
        git clone --progress --single-branch --branch "${INPUTS_BRANCH:-${GITHUB_BRANCH}}" "https://${GITHUB_REPOSITORY_OWNER}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY_OWNER}/${GITHUB_REPOSITORY_NAME}.git" .
      shell: sh
