name: git clone shell action
description: git clone action
author: RekGRpth
inputs:
  branch:
    description: git clone branch
runs:
  using: composite
  steps:
    - env:
        GITHUB_TOKEN: ${{ github.token }}
        INPUTS_BRANCH: ${{ inputs.branch }}
      run: "${GITHUB_ACTION_PATH}/action.sh"
      shell: sh
